DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS welcome;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS homework;
DROP TABLE IF EXISTS lecture;


CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL );


CREATE TABLE welcome (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	greeting TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id) );


CREATE TABLE announcement (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	subject TEXT NOT NULL,
	body TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_text TEXT NOT NULL,
	updated TEXT,
	author_id INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id) );


CREATE TABLE homework (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	Zahl INTEGER NOT NULL,
	due TEXT NOT NULL,
	title TEXT NOT NULL,
	keywords TEXT NOT NULL,
	file_homework TEXT,
	update_ TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id) );


CREATE TABLE lecture (
	id INTEGER PRIMARY KEY NOT NULL,
	Zahl INTEGER NOT NULL,
	week INTEGER NOT NULL,
	day TEXT NOT NULL,
	title TEXT NOT NULL,
	summary TEXT NOT NULL,
	file_lecture TEXT,
	update_ TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id INTEGER NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id) );


